### PR TITLE
Correct `alhorithm` and `{en,de}cript` typos

### PR DESCRIPTION
**Pull request by Benjamin-Loison**
Also note the typo in [the repository *About*](https://github.com/QuasarApp/easyssl):

> This is Qt wrap**p**er of the ssl library.

### CODE REVIEW

**Comment by EndrII** [comment]
O thank you)

**Review by EndrII — APPROVED** [review]
Yes. Spelling has always been my weak point
thank you very much

**Comment by Benjamin-Loison** [comment]
Note that you have not corrected [the *About* typo](https://github.com/QuasarApp/easyssl/pull/5#issue-1976805218), cf the attached screenshot.

image

**Comment by EndrII** [comment]
> Note that you have not corrected [the _About_ typo](https://github.com/QuasarApp/easyssl/pull/5#issue-1976805218), cf the attached screenshot.
> 


done

**Pull request merged**
